production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

mailer:
  default_from_email: <%= ENV["DEFAULT_FROM_EMAIL"] %>

  smtp_settings:
    user_name: <%= ENV["MAILER_USERNAME"] %>
    password: <%= ENV["MAILER_PASSWORD"] %>
    domain: <%= ENV["MAILER_DOMAIN"] %>
    address: <%= ENV["MAILER_ADDRESS"] %>
    authentication: plain
    port: 587
    enable_starttls_auto: true
